### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by DiorsMana** [BeautyOfWeb/ANF#1]
Can you please provide public access to the dataset used in your research paper?

**Comment by tianlema** [comment]
Thank you for your interest in this research. All the original cancer multi-omics data used in this paper was downloaded from GDC (cancer.gov)<https://portal.gdc.cancer.gov/>. We don't have the processed data associated with this paper right now. However, you can download the up-to-date cancer multi-omics data from GDC (cancer.gov)<https://portal.gdc.cancer.gov/> and process the data following the instructions in the paper.
You can also use some simulated data for testing the methods.


________________________________
From: DiorsMana ***@***.***>
Sent: Wednesday, December 13, 2023 1:39 AM
To: BeautyOfWeb/ANF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BeautyOfWeb/ANF] dataset (Issue #1)


Can you please provide public access to the dataset used in your research paper?
